CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  stock INTEGER NOT NULL CHECK (stock >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE orders (
  id UUID PRIMARY KEY,
  user_id TEXT NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  total_price NUMERIC(10, 2) NOT NULL CHECK (total_price >= 0),
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX orders_product_id_idx ON orders(product_id);
CREATE INDEX orders_user_id_idx ON orders(user_id);

INSERT INTO products (id, name, description, price, stock)
VALUES
  (1, 'ScaleLab Mechanical Keyboard', 'A limited launch edition keyboard built for long debugging sessions.', 79.99, 25),
  (2, 'ScaleLab Performance Hoodie', 'A comfortable hoodie for watching dashboards during a traffic spike.', 44.50, 40),
  (3, 'ScaleLab Debug Mug', 'A small batch mug for the first ScaleLab flash sale.', 14.99, 12);

SELECT setval(
  pg_get_serial_sequence('products', 'id'),
  (SELECT MAX(id) FROM products),
  true
);
