apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-shard-0
  namespace: scalelab
spec:
  selector:
    app: postgres-exporter-shard-0
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter-shard-0
  namespace: scalelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter-shard-0
  template:
    metadata:
      labels:
        app: postgres-exporter-shard-0
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.20.1
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_EXPORTER_URL
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-shard-1
  namespace: scalelab
spec:
  selector:
    app: postgres-exporter-shard-1
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter-shard-1
  namespace: scalelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter-shard-1
  template:
    metadata:
      labels:
        app: postgres-exporter-shard-1
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.20.1
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_SHARD_1_EXPORTER_URL
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
